[package]
name = "wrath"
version = "0.2.0"
edition = "2021"
description = "A CLI tool to annihilate any process by name or port"
license = "MIT"

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
sysinfo = "0.39.6"
ureq = { version = "3.4.2", features = ["json"] }
serde = { version = "1.0.229", features = ["derive"] }
anstream = "1.0.0"
anstyle = "1.0.14"
